<a href="https://colab.research.google.com/github/cauancalmeida/Data_Science_studies/blob/main/Estudos%20Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Instrução for

In [1]:
Acessorios = ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva']
Acessorios

['Rodas de liga',
 'Travas elétricas',
 'Piloto automático',
 'Bancos de couro',
 'Ar condicionado',
 'Sensor de estacionamento',
 'Sensor crepuscular',
 'Sensor de chuva']

In [2]:
for item in Acessorios:
  print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva


In [3]:
range(10)

range(0, 10)

In [4]:
for i in range(10):
  print(i**2)

0
1
4
9
16
25
36
49
64
81


In [5]:
quadrado=[]
for i in range(10):
  quadrado.append(i**2)

quadrado

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [6]:
#list comprehensions
[i ** 2 for i in range(10)]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

##Loops Alinhados

In [7]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [8]:
for lista in dados:
    for item in lista: 
        print(item)

Rodas de liga
Travas elétricas
Piloto automático
Bancos de couro
Ar condicionado
Sensor de estacionamento
Sensor crepuscular
Sensor de chuva
Central multimídia
Teto panorâmico
Freios ABS
4 X 4
Painel digital
Piloto automático
Bancos de couro
Câmera de estacionamento
Piloto automático
Controle de estabilidade
Sensor crepuscular
Freios ABS
Câmbio automático
Bancos de couro
Central multimídia
Vidros elétricos


In [9]:
Acessorios = []
for lista in dados:
  for item in lista:
        Acessorios.append(item)
print(Acessorios)

['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva', 'Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento', 'Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']


In [10]:
list(set(Acessorios))

['Teto panorâmico',
 'Controle de estabilidade',
 'Sensor de estacionamento',
 'Sensor de chuva',
 'Travas elétricas',
 'Bancos de couro',
 'Câmbio automático',
 'Central multimídia',
 'Sensor crepuscular',
 'Vidros elétricos',
 'Câmera de estacionamento',
 'Painel digital',
 'Ar condicionado',
 '4 X 4',
 'Freios ABS',
 'Rodas de liga',
 'Piloto automático']

In [11]:
#list comprehentions (resultado instrução) 
list(set([item for lista in dados for item in lista]))

['Teto panorâmico',
 'Controle de estabilidade',
 'Sensor de estacionamento',
 'Sensor de chuva',
 'Travas elétricas',
 'Bancos de couro',
 'Câmbio automático',
 'Central multimídia',
 'Sensor crepuscular',
 'Vidros elétricos',
 'Câmera de estacionamento',
 'Painel digital',
 'Ar condicionado',
 '4 X 4',
 'Freios ABS',
 'Rodas de liga',
 'Piloto automático']

##Condição

In [12]:
# 1º item da lista - Nome do veículo
# 2º item da lista - Ano de fabricação
# 3º item da lista - Veículo é zero km?

dados = [
    ['Jetta Variant', 2003, False],
    ['Passat', 1991, False],
    ['Crossfox', 1990, False],
    ['DS5', 2019, True],
    ['Aston Martin DB4', 2006, False],
    ['Palio Weekend', 2012, False],
    ['A5', 2019, True],
    ['Série 3 Cabrio', 2009, False],
    ['Dodge Jorney', 2019, False],
    ['Carens', 2011, False]
]
dados

[['Jetta Variant', 2003, False],
 ['Passat', 1991, False],
 ['Crossfox', 1990, False],
 ['DS5', 2019, True],
 ['Aston Martin DB4', 2006, False],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Série 3 Cabrio', 2009, False],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [14]:
for carros in dados:
  if carros[2] == True:
    print(carros)

['DS5', 2019, True]
['A5', 2019, True]


In [15]:
#list comprehention
[carros for carros in dados if carros[2] == True]

[['DS5', 2019, True], ['A5', 2019, True]]

In [16]:
for carros in dados:
  if carros[2] == True:
    print(carros[0] +' é zero')
  else:
    print(carros[0]+' não é zero')


Jetta Variant não é zero
Passat não é zero
Crossfox não é zero
DS5 é zero
Aston Martin DB4 não é zero
Palio Weekend não é zero
A5 é zero
Série 3 Cabrio não é zero
Dodge Jorney não é zero
Carens não é zero


In [17]:
A, B, C = [], [], []

for lista in dados:
  if lista[1] <= 2000:
    A.append(lista)
  elif lista[1] > 2000 and lista[1] <= 2010:
    B.append(lista)

In [19]:
A

[['Passat', 1991, False], ['Crossfox', 1990, False]]

In [20]:
B

[['Jetta Variant', 2003, False],
 ['Aston Martin DB4', 2006, False],
 ['Série 3 Cabrio', 2009, False]]

In [22]:
A, B, C = [], [], []

for lista in dados:
  if lista[1] <= 2000:
    A.append(lista)
  elif lista[1] > 2000 and lista[1] <= 2010:
    B.append(lista)
  else:
    C.append(lista)

In [23]:
C

[['DS5', 2019, True],
 ['Palio Weekend', 2012, False],
 ['A5', 2019, True],
 ['Dodge Jorney', 2019, False],
 ['Carens', 2011, False]]

In [24]:
A, B, C = [], [], []

for lista in dados:
  if lista[1] <= 2000:
    A.append(lista)
  elif 2000 < lista[1] <= 2010:
    B.append(lista)
  else:
    C.append(lista)

##Numpy

In [1]:
import numpy

In [3]:
numpy.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
import numpy as np

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
km = np.array([1000, 2300, 4987, 1500])
km

array([1000, 2300, 4987, 1500])

In [7]:
dados = [ 
    ['Rodas de liga', 'Travas elétricas', 'Piloto automático', 'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento', 'Sensor crepuscular', 'Sensor de chuva'],
    ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4', 'Painel digital', 'Piloto automático', 'Bancos de couro', 'Câmera de estacionamento'],
    ['Piloto automático', 'Controle de estabilidade', 'Sensor crepuscular', 'Freios ABS', 'Câmbio automático', 'Bancos de couro', 'Central multimídia', 'Vidros elétricos']
]
dados

[['Rodas de liga',
  'Travas elétricas',
  'Piloto automático',
  'Bancos de couro',
  'Ar condicionado',
  'Sensor de estacionamento',
  'Sensor crepuscular',
  'Sensor de chuva'],
 ['Central multimídia',
  'Teto panorâmico',
  'Freios ABS',
  '4 X 4',
  'Painel digital',
  'Piloto automático',
  'Bancos de couro',
  'Câmera de estacionamento'],
 ['Piloto automático',
  'Controle de estabilidade',
  'Sensor crepuscular',
  'Freios ABS',
  'Câmbio automático',
  'Bancos de couro',
  'Central multimídia',
  'Vidros elétricos']]

In [8]:
Acessorios = np.array(dados)
Acessorios

array([['Rodas de liga', 'Travas elétricas', 'Piloto automático',
        'Bancos de couro', 'Ar condicionado', 'Sensor de estacionamento',
        'Sensor crepuscular', 'Sensor de chuva'],
       ['Central multimídia', 'Teto panorâmico', 'Freios ABS', '4 X 4',
        'Painel digital', 'Piloto automático', 'Bancos de couro',
        'Câmera de estacionamento'],
       ['Piloto automático', 'Controle de estabilidade',
        'Sensor crepuscular', 'Freios ABS', 'Câmbio automático',
        'Bancos de couro', 'Central multimídia', 'Vidros elétricos']],
      dtype='<U24')

In [9]:
km.shape

(4,)

In [10]:
Acessorios.shape

(3, 8)

##Operações com Arrays

In [3]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [4]:
idade = 2019 - anos
idade

array([16, 28, 29,  0, 13])

In [5]:
km_media = km/idade

<ipython-input-5-6e6c1cda6d70>:1: RuntimeWarning: invalid value encountered in true_divide
  km_media = km/idade


In [6]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

## Operações com arrays de duas dimensões 

In [7]:
dados= np.array([km,anos])

In [8]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [9]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [10]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [11]:
km_media=dados[0]/(2019-dados[1])

<ipython-input-11-0c6db78efe80>:1: RuntimeWarning: invalid value encountered in true_divide
  km_media=dados[0]/(2019-dados[1])


In [12]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

##Seleções com Arrays

In [13]:
contador=np.arange(10)

In [14]:
indice=6
index=indice-1
contador[index]

5

###Matriz (indice,coluna) 

In [15]:
dados[1,2]

1990.0

### Fatiamento
A sintaxe para realizar fatiamento em um array Numpy é i:j:k onde i é o índice inicial, j é o índice de parada, e k é o indicador de passo ( k≠0 )

In [16]:
contador=np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
contador[1:4]

array([1, 2, 3])

In [19]:
contador[1:8:2] #do elemento 2 ao elemento 7 de 2 em 2

array([1, 3, 5, 7])

In [20]:
contador[::2] #os pares

array([0, 2, 4, 6, 8])

In [21]:
contador[1::2]

array([1, 3, 5, 7, 9])

In [22]:
dados[: , 1:4]

array([[ 5712., 37123.,     0.],
       [ 1991.,  1990.,  2019.]])

In [24]:
dados[:, 1:3]/(2019- dados[1:3, 1])

array([[ 204.        , 1325.82142857],
       [  71.10714286,   71.07142857]])

###Indexação com array booleano

In [25]:
contador >4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [26]:
contador[contador >4]

array([5, 6, 7, 8, 9])

In [27]:
dados[1]> 2000

array([ True, False, False,  True,  True])

In [28]:
dados[:, dados[1]> 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])

##Atributos Numpy

In [29]:
dados = np.array([[44410.,  5712., 37123.,     0., 25757.], [ 2003.,  1991.,  1990.,  2019.,  2006.]])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [31]:
dados.shape #shape. Esse atributo retorna uma tupla com as dimensões do array.

(2, 5)

In [32]:
dados.ndim #ndim, que retorna o número de dimensões do array.

2

In [33]:
dados.size #size nos mostra o número de elementos de um array.

10

In [34]:
dados.dtype #Para sabermos o tipo de dado dos elementos armazenados no array

dtype('float64')

In [35]:
dados.T #O atributo T nos retorna o array transposto, ou seja, ele transpõe uma matriz, convertendo linhas em colunas e vice-versa.

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [36]:
dados.transpose() #mesma funcionalidade do atributo T

array([[44410.,  2003.],
       [ 5712.,  1991.],
       [37123.,  1990.],
       [    0.,  2019.],
       [25757.,  2006.]])

In [37]:
dados.tolist() # transforma um array Numpy em uma lista do Python.

[[44410.0, 5712.0, 37123.0, 0.0, 25757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

###O método reshape() retorna um array contendo os mesmos dados, mas com uma nova forma.

In [38]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [39]:
contador.reshape((5,2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [40]:
contador.reshape((5, 2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [41]:
contador.reshape((5, 2), order='F')

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [42]:
km = [44410, 5712, 37123, 0, 25757]
anos = [2003, 1991, 1990, 2019, 2006]

In [43]:
info_carros = km + anos
info_carros

[44410, 5712, 37123, 0, 25757, 2003, 1991, 1990, 2019, 2006]

In [44]:
np.array(info_carros)

array([44410,  5712, 37123,     0, 25757,  2003,  1991,  1990,  2019,
        2006])

In [45]:
np.array(info_carros).reshape((2, 5))

array([[44410,  5712, 37123,     0, 25757],
       [ 2003,  1991,  1990,  2019,  2006]])

In [46]:
np.array(info_carros).reshape((5, 2))

array([[44410,  5712],
       [37123,     0],
       [25757,  2003],
       [ 1991,  1990],
       [ 2019,  2006]])

In [47]:
np.array(info_carros).reshape((5, 2), order='F')

array([[44410,  2003],
       [ 5712,  1991],
       [37123,  1990],
       [    0,  2019],
       [25757,  2006]])

###resize(), que altera a forma e o tamanho do array.

In [48]:
dados_new = dados.copy()
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [49]:
dados_new.resize((3, 5))

ValueError: ignored

In [50]:
dados_new.resize((3, 5), refcheck=False)
dados_new

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.],
       [    0.,     0.,     0.,     0.,     0.]])

In [51]:
dados_new[2] = dados_new[0] / (2019 - dados_new[1])
dados_new

<ipython-input-51-820700e04a2b>:1: RuntimeWarning: invalid value encountered in true_divide
  dados_new[2] = dados_new[0] / (2019 - dados_new[1])


array([[44410.        ,  5712.        , 37123.        ,     0.        ,
        25757.        ],
       [ 2003.        ,  1991.        ,  1990.        ,  2019.        ,
         2006.        ],
       [ 2775.625     ,   204.        ,  1280.10344828,            nan,
         1981.30769231]])

## Estatisticas com Numpy

In [53]:
anos = np.loadtxt(fname = "/Data/carros-anos.txt", dtype = int)
km = np.loadtxt(fname = "/Data/carros-km.txt")
valor = np.loadtxt(fname = "/Data/carros-valor.txt")

In [ ]:
dataset = np.column_stack((anos, km, valor))
dataset


In [56]:
dataset.shape

(258, 3)

### np.mean media

In [57]:
np.mean(dataset, axis = 0) #media por coluna

array([ 2007.51162791, 44499.41472868, 98960.51310078])

In [58]:
np.mean(dataset[:,1]) #media de KM 

44499.41472868217

In [59]:
np.mean(dataset[:,2]) #media valor

98960.51310077519

### np.std desvio padrao

In [60]:
np.std(dataset[:,2])

29754.101150388564

### np.sum somatoria

In [61]:
dataset.sum(axis = 0)

array([  517938.        , 11480849.        , 25531812.37999999])

In [64]:
dataset[: 2].sum() #somatoria de valor

248356.58000000002